name: EKS Infrastructure deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: us-east-1

      - name: Verify authentication
        run: aws sts get-caller-identity

      - name: Tofu Deploy AWS/Cluster1
        uses: ./.github/workflows/tofu.yml
        with:
          tfvar_path: 'cluster/cluster.tfvars'
