name: EKS Infrastructure deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  cluster-1:
    uses: ./.github/workflows/tofu.yml
    with:
      tfvar_path: cluster1/cluster.tfvars
      ref_name: cluster1
    secrets: inherit

  cluster-2:
    uses: ./.github/workflows/tofu.yml
    with:
      tfvar_path: cluster2/cluster.tfvars
      ref_name: cluster2
    secrets: inherit
