name: EKS Infrastructure deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  tofu-deploy-cluster-1:
    uses: ./.github/workflows/tofu.yml
    with:
      tfvar_path: 'cluster/cluster.tfvars'

