name: EKS Infrastructure deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  tofu-deploy-cluster-1:
    uses: ./.github/workflows/tofu.yml
    with:
      tfvar_path: './cluster1/cluster.tfvars'
    secrets: inherit

  tofu-deploy-cluster-2:
    uses: ./.github/workflows/tofu.yml
    with:
      tfvar_path: './cluster2/cluster.tfvars'
    secrets: inherit

