name: EKS Infrastructure deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: us-east-1

      - name: Verify authentication
        run: aws sts get-caller-identity

  tofu-deploy-cluster-1:
    needs: prepare
    uses: ./.github/workflows/tofu.yml
    with:
      tfvar_path: cluster1/cluster.tfvars
      tfstate_name: cluster1.tfstate
    secrets: inherit

  tofu-deploy-cluster-2:
    needs: prepare
    uses: ./.github/workflows/tofu.yml
    with:
      tfvar_path: cluster2/cluster.tfvars
      tfstate_name: cluster2.tfstate
    secrets: inherit
