name: EKS Infrastructure Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  cluster-1:
    uses: ./.github/workflows/tofu-destroy.yml
    with:
      ref_name: cluster1
    secrets: inherit

  cluster-2:
    uses: ./.github/workflows/tofu-destroy.yml
    with:
      ref_name: cluster2
    secrets: inherit
