name: Tofu Apply Workflow

on:
  workflow_call:
    inputs:
      tfvar_path:
        type: string
        description: 'Path to the cluster `tfvar` file'
        required: true
      tfstate_name:
        type: string
        description: 'Name of the tfstate filename'
        required: true

jobs:
  tofu-plan-apply:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.9.0

      - name: Initialize OpenTofu
        run: tofu init -var-file ${{ github.workspace }}/${{ inputs.tfvar_path }}

      - name: Validate OpenTofu
        run: tofu validate -var-file ${{ github.workspace }}/${{ inputs.tfvar_path }} -var 'tfstate_name=${{ inputs.tfstate_name }}'

      - name: Run OpenTofu Plan
        run: tofu plan -var-file ${{ github.workspace }}/${{ inputs.tfvar_path }} -var 'tfstate_name=${{ inputs.tfstate_name }}' -out=${{ inputs.tfstate_name }}.tfplan

      - name: Apply OpenTofu Plan
        run: tofu apply -auto-approve ${{ inputs.tfstate_name }}.tfplan
