name: Tofu Apply Workflow

on:
  workflow_call:
    inputs:
      tfvar_path:
        type: string
        description: 'Path to the cluster `tfvar` file'
        required: true

jobs:
  tofu-plan-apply:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: us-east-1

      - name: Verify authentication
        run: aws sts get-caller-identity

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.9.0

      - name: Initialize OpenTofu
        run: tofu init -var-file ${{ inputs.tfvar_path }}

      - name: Validate OpenTofu
        run: tofu validate -var-file ${{ inputs.tfvar_path }}

      - name: Run OpenTofu Plan
        run: tofu plan -var-file ${{ inputs.tfvar_path }} -out=tfplan

      - name: Apply OpenTofu Plan
        run: tofu apply -auto-approve tfplan
